FROM openjdk:17-jdk-alpine
MAINTAINER baeldung.com
COPY target/department-service-0.0.1-SNAPSHOT.jar department-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/department-service-0.0.1-SNAPSHOT.jar"]